# Generated by Django 3.2 on 2023-07-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=100, verbose_name='Author '),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='books', to='bookstore.Category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='editor',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Editor '),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='bookstore.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title '),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='shipping_info',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='bookstore.shippinginfo', verbose_name='Shipping Info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.client', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ShippingInfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bookstore.shippinginfo', verbose_name='ShippingInfo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(related_name='orders', to='bookstore.Book', verbose_name='books'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.client', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='address',
            field=models.CharField(max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='city',
            field=models.CharField(max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='country',
            field=models.CharField(default='', max_length=255, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='name',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='postal_code'),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='state',
            field=models.CharField(blank=True, max_length=255, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='books',
            field=models.ManyToManyField(blank=True, to='bookstore.Book', verbose_name='books'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title ')),
                ('content', models.TextField(blank=True, verbose_name='description')),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='bookstore.Category', verbose_name='categories')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='bookstore.Tag', verbose_name='tags')),
            ],
        ),
    ]
