# Generated by Django 3.2 on 2023-07-17 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore', '0002_auto_20230717_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='user'),
            preserve_default=False,
        ),
    ]
