# Generated by Django 3.2 on 2023-07-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20230717_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at', 'title'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='shippinginfo',
            options={'verbose_name': 'Shipping information', 'verbose_name_plural': 'Shipping information'},
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Name'),
        ),
    ]
