# Generated by Django 3.2 on 2023-07-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_auto_20230720_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
    ]
