# Generated by Django 3.2 on 2023-07-26 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_auto_20230726_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='books',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipping', 'Shipping'), ('shipped', 'Shipped')], default='pending', max_length=32, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookstore.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookstore.order')),
            ],
            options={
                'unique_together': {('book', 'order')},
            },
        ),
    ]
