# Generated by Django 3.2 on 2023-07-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0018_book_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.CharField(blank=True, max_length=4, verbose_name='Year of publication'),
        ),
    ]
