# Generated by Django 3.2 on 2023-07-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0019_auto_20230731_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.CharField(blank=True, max_length=5, verbose_name='Pages'),
        ),
    ]
