# Generated by Django 3.2 on 2023-07-31 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0020_book_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ShippingInfo',
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bookstore.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='bookstore.client', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('books', models.ManyToManyField(to='bookstore.Book', verbose_name='Books')),
                ('user', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.client', verbose_name='User')),
            ],
        ),
    ]
