# Generated by Django 3.2 on 2023-08-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0023_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bookstoreapi/books/images', verbose_name='Image'),
        ),
    ]
